---
extends: eslint:recommended
env:
    browser: true
    es6: true
globals:
    THREE: false
    ThreeBSP: false
    math: false
    sweetAlert: false
    Detector: false
parserOptions:
    ecmaVersion: 6
rules:
    no-console: 0
    no-extra-parens: 1
    no-unexpected-multiline: 2
    accessor-pairs: 1
    block-scoped-var: 1
    curly: 1
    dot-notation: 1
    eqeqeq:
        - 1
        - smart
    keyword-spacing: 
        - 2
        - 
            after: false
            overrides: 
                case: 
                    after: true
                return: 
                    after: true
                throw: 
                    after: true
    no-caller: 2
    no-confusing-arrow: 1
    no-constant-condition: 1
    no-eq-null: 1
    no-extend-native: 2
    no-extra-bind: 1
    no-floating-decimal: 1
    no-implicit-coercion: 1
    no-implied-eval: 1
    no-invalid-this: 2
    no-iterator: 1
    no-labels: 1
    no-lone-blocks: 2
    no-loop-func: 1
    no-multi-spaces: 2
    no-multi-str: 1
    no-native-reassign: 2
    no-new-func: 2
    no-new-wrappers: 1
    no-new: 2
    no-octal-escape: 2
    no-proto: 2
    no-return-assign: 2
    no-script-url: 2
    no-self-compare: 1
    no-unused-expressions: 2
    no-useless-call: 1
    no-useless-concat: 1
    no-void: 2
    yoda: 1
    no-label-var: 2
    no-shadow-restricted-names: 2
    no-shadow: 2
    no-undef-init: 1
    array-bracket-spacing: 2
    block-spacing: 2
    brace-style:
        - 2
        - allman
        - allowSingleLine: false
    camelcase: 2
    comma-spacing: 2
    comma-style: 2
    computed-property-spacing: 2
    consistent-this: 1
    eol-last: 1
    indent:
        - 2
        - tab
    key-spacing: 2
    new-cap: 1
    new-parens: 2
    no-array-constructor: 2
    no-lonely-if: 2
    no-multiple-empty-lines: 2
    no-negated-condition: 1
    no-new-object: 1
    no-spaced-func: 2
    no-trailing-spaces: 2
    no-underscore-dangle: 2
    no-unneeded-ternary: 1
    object-curly-spacing: 2
    operator-assignment: 1
    padded-blocks:
        - 2
        - never
    quote-props:
        - 2
        - as-needed
    quotes: 2
    semi: 2
    space-before-function-paren:
        - 2
        - never
    space-in-parens: 2
    space-infix-ops: 2
    object-shorthand: 1
    prefer-spread: 1
