---
rules:
    block-closing-brace-newline-after: always
    block-closing-brace-newline-before: always
    block-no-empty: true
    block-no-single-line: true
    block-opening-brace-newline-after: always
    block-opening-brace-newline-before: always
    color-hex-case: upper
    color-hex-length: long
    color-named: always-where-possible
    color-no-invalid-hex: true
    custom-property-no-outside-root: true
    declaration-bang-space-after: never
    declaration-bang-space-before: always
    declaration-block-no-duplicate-properties: true
    declaration-block-no-shorthand-property-overrides: true
    declaration-block-semicolon-newline-after: always
    declaration-block-semicolon-newline-before: never-multi-line
    declaration-block-semicolon-space-before: never
    declaration-block-single-line-max-declarations: 1
    declaration-block-trailing-semicolon: always
    declaration-colon-space-after: always-single-line
    declaration-colon-space-before: never
    font-family-name-quotes: single-unless-keyword
    font-weight-notation: named-where-possible
    function-comma-newline-after: always-multi-line
    function-comma-newline-before: never-multi-line
    function-comma-space-after: always-single-line
    function-comma-space-before: never-single-line
    function-linear-gradient-no-nonstandard-direction: true
    function-parentheses-space-inside: never
    function-url-quotes: single
    function-whitespace-after: always
    indentation: tab
    max-empty-lines: 1
    no-descending-specificity: true
    no-duplicate-selectors: true
    no-eol-whitespace: true
    no-invalid-double-slash-comments: true
    no-missing-end-of-source-newline: true
    no-unknown-animations: true
    number-leading-zero: always
    number-no-trailing-zeros: true
    root-no-standard-properties: true
    rule-nested-empty-line-before: never
    rule-non-nested-empty-line-before: always
    selector-combinator-space-after: always
    selector-combinator-space-before: always
    selector-list-comma-newline-after: always-multi-line
    selector-list-comma-newline-before: never-multi-line
    selector-list-comma-space-after: always-single-line
    selector-list-comma-space-before: never
    string-no-newline: true
    string-quotes: single
    value-list-comma-space-after: always-single-line
    zero-length-no-unit: true
